[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "debug-print", "with-chrono", "with-json", "with-uuid"] }
serde = "1.0.215"
serde_json = "1.0.133"
